source_repo: foruck__awesome-human-motion
source_url: https://github.com/Foruck/Awesome-Human-Motion
collect_log: _private/PaperBite/github_awesome/collect_logs/Foruck__Awesome-Human-Motion.auto.csv
source_type: github_awesome_collect_log
enabled: true
updated_at: 2026-04-22T22:30:10+08:00
